version: "3.7"

services:
  cloudflare-dns-sync:
    build: "https://raw.githubusercontent.com/batscs/docker-cloudflare-dns-sync/main/Dockerfile"
    image: "batscs/cloudflare-dns-sync"
    container_name: "cloudflare-dns-sync"
    restart: unless-stopped
    volumes:
      - "./data:/app/data"
